<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Active regular expression' => '',
  'Add child' => '',
  'Additional' => '',
  'All' => '',
  'An internal server error occurred.' => '',
  'Are you sure to delete this item?' => '',
  'Available layouts for pages' => '',
  'Available locales' => '',
  'Back to index' => '',
  'Backend authorization route' => '',
  'Bad file.' => '',
  'CSS Class' => '',
  'Copy' => '',
  'Create' => '',
  'Create Page' => '',
  'Create Time' => '',
  'Create User ID' => '',
  'Create new pages' => '',
  'Default' => '',
  'Delete' => '',
  'Delete pages' => '',
  'Enabled' => '',
  'Error' => '',
  'For all' => '',
  'ID' => '',
  'Layout' => '',
  'Link' => '',
  'List separated by commas. Example: <code>default, narrow</code>' => '',
  'List separated by commas. Example: <code>ru, en</code>' => '',
  'Locale' => '',
  'Manage menu' => '',
  'Menu' => '',
  'Menu manager' => '',
  'Meta Description' => '',
  'Meta Keywords' => '',
  'Meta description for all website' => '',
  'Meta keywords for all website' => '',
  'Mode down' => '',
  'Move up' => '',
  'Only for administrators' => '',
  'Only for authorized users' => '',
  'Page title.' => '',
  'Pages' => '',
  'Pages manager' => '',
  'Parent ID' => '',
  'Preg' => '',
  'Provides authorization and password reset (with captcha) for backend application.' => '',
  'Publication' => '',
  'Published' => '',
  'Save' => '',
  'Settings' => '',
  'Slug' => '',
  'Sort' => '',
  'Text' => '',
  'The requested page does not exist.' => '',
  'Title' => '',
  'URL where page will be published. Example: <code>/index</code> will be <code>{domain}/index</code>.' => '',
  'Unpublished' => '',
  'Update' => '',
  'Update Page: {name}' => '',
  'Update Time' => '',
  'Update User ID' => '',
  'Update pages' => '',
  'View' => '',
  'View pages' => '',
  'Website' => '',
  'Window Title' => '',
  'Window title for website' => '',
  'Window title. May be longer than page title.' => '',
  '_module_description_' => '',
  '_module_name_' => '',
);
