<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Active regular expression' => 'Регулярное выр. активности',
  'Add child' => 'Добавить дочерний элемент',
  'Additional' => 'Дополнительно',
  'An internal server error occurred.' => 'Внутренняя ошибка сервера.',
  'Back to index' => 'На главную',
  'Backend authorization route' => '',
  'CSS Class' => 'CSS Класс',
  'Create Time' => 'Время создания',
  'Create User ID' => 'Создал пользователь',
  'Create new pages' => 'Создать новые страницы',
  'Delete' => 'Удалить',
  'Delete pages' => 'Удалить страницы',
  'Enabled' => 'Активность',
  'Error' => 'Ошибка',
  'ID' => 'ID',
  'Link' => 'Ссылка',
  'Manage menu' => 'Управление меню',
  'Menu' => 'Меню',
  'Menu manager' => 'Менеджер меню',
  'Mode down' => 'Ниже',
  'Move up' => 'Выше',
  'Pages' => 'Страницы',
  'Pages manager' => 'Менеджер страниц',
  'Parent ID' => 'Родитель',
  'Preg' => 'Регулярное выражение',
  'Provides authorization and password reset (with captcha) for backend application.' => '',
  'Save' => 'Сохранить',
  'Sort' => 'Сортировка',
  'Title' => 'Заголовок',
  'Update Time' => 'Время обновления',
  'Update User ID' => 'Обновил пользователь',
  'Update pages' => 'Обновление страниц',
  'View pages' => 'Просмотр страниц',
  'Website' => 'Веб-сайт',
  '_module_description_' => 'Управляет меню и страницами сайта.',
  '_module_name_' => 'Веб-сайт',
);
