<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Active regular expression' => 'Регулярное выр. активности',
  'Add child' => 'Добавить дочерний элемент',
  'Additional' => 'Дополнительно',
  'All' => 'Все',
  'An internal server error occurred.' => 'Внутренняя ошибка сервера.',
  'Are you sure to delete this item?' => 'Вы верены, что хотите удалить этот элемент?',
  'Available layouts for pages' => 'Доступные шаблоны для страниц',
  'Available locales' => 'Доступные локали',
  'Back to index' => 'На главную',
  'Backend authorization route' => '',
  'Bad file.' => 'Плохой файл.',
  'CSS Class' => 'CSS Класс',
  'Copy' => 'Скопировать',
  'Create' => 'Создать',
  'Create Page' => 'Создать страницу',
  'Create Time' => 'Время создания',
  'Create User ID' => 'Создал пользователь',
  'Create new pages' => 'Создать новые страницы',
  'Default' => 'По-умолчанию',
  'Default layout' => 'Шаблон для страниц по-умолчанию',
  'Delete' => 'Удалить',
  'Delete pages' => 'Удалить страницы',
  'Enabled' => 'Активность',
  'Error' => 'Ошибка',
  'For all' => 'Для всех',
  'ID' => 'ID',
  'Layout' => 'Шаблон',
  'Link' => 'Ссылка',
  'List separated by commas. Example: <code>default, narrow</code>. Also you can use labels: <code>default:Default layout, base:Base without container</code>.' => 'Список через запятую. Например: <code>default, narrow</code>. Также можно дать названия шаблонам: <code>default:Стандартный, base:Базовый без контейнера</code>',
  'List separated by commas. Example: <code>ru, en</code>' => 'Список через запятую. Например: <code>ru, en</code>',
  'Locale' => 'Локаль',
  'Manage menu' => 'Управление меню',
  'Menu' => 'Меню',
  'Menu manager' => 'Менеджер меню',
  'Meta Description' => '',
  'Meta Keywords' => '',
  'Meta description for all website' => 'Meta description для всех страниц',
  'Meta keywords for all website' => 'Meta keywords для всех страниц',
  'Mode down' => 'Ниже',
  'Move up' => 'Выше',
  'Only for administrators' => 'Только для администраторов',
  'Only for authorized users' => 'Только для авторизованных пользователй',
  'Page "{url}" not found.' => 'Страница "{url}" не найдена.',
  'Page title.' => 'Заголовок страницы.',
  'Pages' => 'Страницы',
  'Pages manager' => 'Менеджер страниц',
  'Parent ID' => 'Родитель',
  'Preg' => 'Регулярное выражение',
  'Provides authorization and password reset (with captcha) for backend application.' => '',
  'Publication' => 'Публикация',
  'Published' => 'Публикация',
  'Return back' => 'Назад',
  'Save' => 'Сохранить',
  'Settings' => 'Настройки',
  'Slug' => 'URL (идентификатор)',
  'Sort' => 'Сортировка',
  'Structure' => 'Структура',
  'Text' => 'Текст',
  'The requested page does not exist.' => 'Запрашиваемая страница не существует.',
  'Title' => 'Заголовок',
  'URL where page will be published. Example: <code>/index</code> will be <code>{domain}/index</code>.' => 'URL по которому будет доступна страница. Пример: <code>/index</code> будет доступна по адресу <code>{domain}/index</code>.',
  'Unpublished' => 'Скрыто',
  'Update' => 'Обновить',
  'Update Page: {name}' => 'Обновить страницу: {name}',
  'Update Time' => 'Время обновления',
  'Update User ID' => 'Обновил пользователь',
  'Update pages' => 'Обновление страниц',
  'View' => 'Просмотр',
  'View pages' => 'Просмотр страниц',
  'Website' => 'Веб-сайт',
  'Window Title' => 'Заголовок окна',
  'Window title for website' => 'Заголовок окна для всего сайта',
  'Window title. May be longer than page title.' => 'Заголовок окна. Может быть длинее заголовка страницы.',
  'You must be authenticated to view this page.' => '',
  '_module_description_' => 'Управляет меню и страницами сайта.',
  '_module_name_' => 'Веб-сайт',
);
