<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Common' => 'Общее',
    'Counters JavaScript' => 'Код счетчиков (JS)',
    'Default layout' => 'Шаблон по-умолчанию',
    'Generate using title' => 'Сгенерировать из заголовка',
    'Google, LiveInternet, etc.' => 'Google, LiveInternet, etc.',
    'Page not found.' => 'Страница не найдена.',
    'SEO' => 'SEO',
    'Website. View hidden pages' => 'Веб-сайт. Просмотр скрытых страниц.',
    'You must be authenticated to view this page.' => 'Вы должны быть авторизованы для просмотра этой страницы.',
    'Active' => 'Активна',
    'Are you sure want to delete this translation?' => 'Вы уверены, что хотите удалить этот перевод?',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту страницу?',
    'As this page will look like.' => 'Как страница будет выглядеть.',
    'Auth users only' => 'Только для пользователей',
    'Common info' => 'Общая информация',
    'Configuration' => 'Настройка',
    'Content' => 'Контент',
    'Create page' => 'Создать страницу',
    'Created At' => 'Создан в',
    'Created By' => 'Создал',
    'Css Class' => 'CSS класс',
    'Default' => 'По-умолчанию',
    'Default Language' => 'Язык по-умолчанию',
    'Delete' => 'Удалить',
    'Delete this translation' => 'Удалить текущий перевод',
    'Draft' => 'Черновик',
    'Element ID' => 'ID элемента',
    'Enabled' => 'Включен',
    'Hidden' => 'Скрыта',
    'ID' => 'ID',
    'If needed language version not found, which version should use?' => 'Если запрашиваемый язык не найден, то какой язык использовать?',
    'Keywords of the page separated by commas. Example: <code>bread, cookies</code>.' => 'Ключевые слова через запятую. Пример: <code>спорт, футбол</code>.',
    'Language' => 'Язык',
    'Layout' => 'Шаблон',
    'Link' => 'Ссылка',
    'Menu' => 'Меню',
    'Menus' => 'Меню',
    'Not use' => 'Не использовать',
    'Page ID' => 'ID страницы',
    'Page title for Search Engines.' => 'Заголовок страниц для поисковых систем.',
    'Pages' => 'Страницы',
    'Parent ID' => 'Родитель',
    'Preg' => 'Рег. выражение',
    'Preview page' => 'Предпросмотр страницы',
    'Reset' => 'Сбросить',
    'SEO: Description' => 'SEO: Описание',
    'SEO: Keywords' => 'SEO: Ключевые слова',
    'SEO: Title' => 'SEO: Заголовок',
    'Save' => 'Сохранить',
    'Save and create new' => 'Сохранить и создать еще',
    'Save and exit' => 'Сохранить и выйти',
    'Saved.' => 'Сохранено.',
    'Search' => 'Поиск',
    'Short description of the page.' => 'Краткое описание страницы.',
    'Slug' => 'URL',
    'Sort' => 'Сортировка',
    'Status' => 'Статус',
    'Target' => 'Цель',
    'Text' => 'Текст',
    'Text format' => 'Формат текста',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует.',
    'Title' => 'Заголовок',
    'Translations' => 'Переводы',
    'URL where page will be published. Example: <code>index</code> will be <code>{domain}/{language}/index</code>.' => 'URL по которому будет доступна страница. Пример: <code>/index</code> будет доступна по адресу <code>{domain}/index</code>.',
    'Update' => 'Редактировать',
    'Update page' => 'Редактировать страницу',
    'Updated At' => 'Обновлен в',
    'Updated By' => 'Обновил',
    'Website' => 'Веб-сайт',
    'Website Module' => 'Модуль Веб-сайт',
    'Website. Change SEO settings' => 'Веб-сайт. Менять настройки SEO.',
    'Website. Create pages' => 'Веб-сайт. Создавать страницы.',
    'Website. Create, update and delete menus' => 'Веб-сайт. Создавать, обновлять и удалять меню.',
    'Website. Delete pages' => 'Веб-сайт. Удалять страницы',
    'Website. Manage menus' => 'Веб-сайт. Управлять меню',
    'Website. Manage pages' => 'Веб-сайт. Управлять страницами',
    'Website. Update pages' => 'Веб-сайт. Обновлять страницами',
    'Website. View pages' => 'Веб-сайт. Просматривать страницы',
    'Who will see this page?' => 'Кто увидит эту страницу?',
];
